default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: leoni_api_development

test:
  <<: *default
  database: leoni_api_test

production:
  <<: *default
  database: leoni_api_production
  username: leoni
  password: <%= ENV['JAMIN_DATABASE_PASSWORD'] %>
